export * from "@/widgets/tables/components/loadingtable";
export * from "@/widgets/tables/components/pagination";
export * from "@/widgets/tables/qa-table";
export * from "@/widgets/tables/user-table";
export * from "@/widgets/tables/programme-table";
export * from "@/widgets/tables/major-table";
export * from "@/widgets/tables/tuition-table";
export * from "@/widgets/tables/scholarship-table";
export * from "@/widgets/tables/feedback-table";